### ISSUE TITLE
NEST theme will not display Comments 

### ISSUE THREAD

**Issue by MasterWayne2759** [zendesklabs/themes#16]
Nest theme article_page.hbs will not display comments on the page even after adding the code (recommended by Zendesk Support) 
[comment_block.txt](https://github.com/zendesklabs/themes/files/3453264/comment_block.txt)

![Screen Shot 2019-07-31 at 12 06 17 PM](https://user-images.githubusercontent.com/30160815/62236119-a9aca200-b38b-11e9-9222-0ac615cfa7d5.png)

**Comment by ts-1** [comment]
@MasterWayne2759 you don't have to add the code as recommended by Zendesk Support because of the difference in the code of the two themes, it will not work for you.

The Nest theme will show comments by default as I see there is no such setting to hide the comments. If the comments are not visible to you for the articles then please make sure that the comments are enabled for the article.

Take a look at this article to see how to enable and disable the comments for a particular article: https://support.zendesk.com/hc/en-us/articles/115002382627-Disabling-comments-for-an-article

**Comment by ts-1** [comment]
@MasterWayne2759 you can take a look at this https://github.com/ts-1/themes/blob/patch-3/nest_theme/templates/article_page.hbs to show comments on article template.
